/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer;

import javax.swing.JOptionPane;
import control.GUIManager;

/**
 *
 * @author correia
 */
public class JFrMenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public JFrMenuInicial() {
        this.setSize(520,800);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoVendas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoEstoque = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botaoCaixa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botaoCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botaoNotaFiscal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setBackground(new java.awt.Color(255, 255, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        botaoVendas.setBackground(new java.awt.Color(204, 204, 204));
        botaoVendas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVendasMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buy-50.png"))); // NOI18N
        jLabel1.setText("Vendas");

        javax.swing.GroupLayout botaoVendasLayout = new javax.swing.GroupLayout(botaoVendas);
        botaoVendas.setLayout(botaoVendasLayout);
        botaoVendasLayout.setHorizontalGroup(
            botaoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoVendasLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoVendasLayout.setVerticalGroup(
            botaoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        botaoEstoque.setBackground(new java.awt.Color(204, 204, 204));
        botaoEstoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEstoqueMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stock-50.png"))); // NOI18N
        jLabel2.setText("Estoque");

        javax.swing.GroupLayout botaoEstoqueLayout = new javax.swing.GroupLayout(botaoEstoque);
        botaoEstoque.setLayout(botaoEstoqueLayout);
        botaoEstoqueLayout.setHorizontalGroup(
            botaoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoEstoqueLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoEstoqueLayout.setVerticalGroup(
            botaoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        botaoCaixa.setBackground(new java.awt.Color(204, 204, 204));
        botaoCaixa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCaixaMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cash-register-50.png"))); // NOI18N
        jLabel3.setText("Caixa");

        javax.swing.GroupLayout botaoCaixaLayout = new javax.swing.GroupLayout(botaoCaixa);
        botaoCaixa.setLayout(botaoCaixaLayout);
        botaoCaixaLayout.setHorizontalGroup(
            botaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoCaixaLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoCaixaLayout.setVerticalGroup(
            botaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoCaixaLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botaoCliente.setBackground(new java.awt.Color(204, 204, 204));
        botaoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoClienteMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/client-50.png"))); // NOI18N
        jLabel4.setText("Cliente");

        javax.swing.GroupLayout botaoClienteLayout = new javax.swing.GroupLayout(botaoCliente);
        botaoCliente.setLayout(botaoClienteLayout);
        botaoClienteLayout.setHorizontalGroup(
            botaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoClienteLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botaoClienteLayout.setVerticalGroup(
            botaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        botaoNotaFiscal.setBackground(new java.awt.Color(204, 204, 204));
        botaoNotaFiscal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoNotaFiscal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoNotaFiscal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoNotaFiscalMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nota-fiscal-50.png"))); // NOI18N
        jLabel5.setText("Nota Fiscal");

        javax.swing.GroupLayout botaoNotaFiscalLayout = new javax.swing.GroupLayout(botaoNotaFiscal);
        botaoNotaFiscal.setLayout(botaoNotaFiscalLayout);
        botaoNotaFiscalLayout.setHorizontalGroup(
            botaoNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoNotaFiscalLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        botaoNotaFiscalLayout.setVerticalGroup(
            botaoNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NEW STORE!.png"))); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVendasMouseClicked
        // TODO add your handling code here:
        GUIManager.getInstance().openWindowVendas();
    }//GEN-LAST:event_botaoVendasMouseClicked

    private void botaoEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEstoqueMouseClicked
        // TODO add your handling code here:
        GUIManager.getInstance().openWindowEstoque();
    }//GEN-LAST:event_botaoEstoqueMouseClicked

    private void botaoCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCaixaMouseClicked
        // TODO add your handling code here:
        GUIManager.getInstance().openWindowCaixa();
    }//GEN-LAST:event_botaoCaixaMouseClicked

    private void botaoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoClienteMouseClicked
        // TODO add your handling code here:
        GUIManager.getInstance().openWindowCliente();
    }//GEN-LAST:event_botaoClienteMouseClicked

    private void botaoNotaFiscalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNotaFiscalMouseClicked
        // TODO add your handling code here:
        GUIManager.getInstance().openWindowNotaFiscal();
    }//GEN-LAST:event_botaoNotaFiscalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoCaixa;
    private javax.swing.JPanel botaoCliente;
    private javax.swing.JPanel botaoEstoque;
    private javax.swing.JPanel botaoNotaFiscal;
    private javax.swing.JPanel botaoVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
